# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -v -tags sqlite -o ./testfixtures{{exeExt}} ./cmd/testfixtures

  lint:
    desc: Runs golangci-lint
    cmds:
      - go list -f '{{"{{.Dir}}"}}' -m | xargs -I@ sh -c 'cd @ && pwd && golangci-lint run'

  test-cli:
    cmds:
      - ./testfixtures -d sqlite -c testdb.sqlite3 -D testdata/fixtures

  test:pg:
    desc: Test PostgreSQL
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestPostgreSQL}

  test:mysql:
    desc: Test MySQL
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestMySQL}

  test:sqlite:
    desc: Test SQLite
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestSQLite}

  test:sqlserver:
    desc: Test SQLServer
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestSQLServer}

  test:crdb:
    desc: Test CockroachDB
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestCockroachDB}

  test:clickhouse:
    desc: Test Clickhouse
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestClickhouse}

  test:spanner:
    desc: Test Spanner with GoogleSQL dialect
    cmds:
      - task: test-db
        vars: {TEST_NAME: TestSpanner}

  test-db:
    cmds:
      -  go test work -v -run {{.TEST_NAME}} ./...

  goreleaser:test:
    desc: Tests release process without publishing
    cmds:
      - goreleaser --snapshot --clean

  test-all:
    cmds:
      - go test work -v ./...
